### ISSUE TITLE
Interop server runs incredibly slow

### ISSUE THREAD

**Issue by juanvallejo** [auvsi-suas/interop#11] opened 2015-11-05 03:20 UTC
While running the interop server on an Ubuntu machine, four instances of the Python web server gateway interface (WSGI) run at the same time in the background. This appears to make the machine extremely slow / unresponsive to work with.

**Comment by prattmic** [comment] 2015-11-05 05:07
If you are certain that is multiple instances of the server are affecting your performance, you can change it on your installation. Either modify the [Puppet config](https://github.com/auvsi-suas/interop/blob/master/setup/puppet_files/auvsi_suas/manifests/apache_setup.pp#L51-L53) and rerun ``setup.sh``/``vagrant provision``, or by directly modifying ``/etc/apache2/sites-enabled/25-interop_server.conf`` and restarting Apache (though Puppet will overwrite this file when it runs again.

Four instances of the server were selected primarily to get the most out of a fairly powerful machine, not a small test machine.

That said, I am skeptical that multiple instances would make your machine extremely slow, unless your machine has very little resources. Each instance should sit idle on CPU except when servicing a request. On my test machine, each instance is using ~50MB of resident memory.

What are you using for your test machine, a physical machine or a Vagrant VM?  If you are using Vagrant, see #8 and #10 for discussion of the poor performance of Virtualbox's shared folders. Though that has thus far we have only seen significant impact on the latency of the first few requests.

**Comment by legonigel** [comment] 2015-11-06 19:44
I think the issue @juanvallejo is seeing is related to #13. I am working with Juan and we think #13 might be the cause of our bad performance.

**Comment by pmtischler** [comment] 2015-11-11 20:02
Closing as duplicate of #13.

**Closed by pmtischler** 2015-11-11 20:02 UTC
